name: CI Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev

jobs:
  CIFlow:
    runs-on: buildserver
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -R $GITHUB_WORKSPACE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build
        run: |
          docker build -t wusa889/c:latest .
