name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev

jobs:
  ci-pipeline:
    runs-on: buildserver
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build
        run: |
          docker build -t wusa889/LB324:latest .
